# Generated by Django 5.0.6 on 2024-06-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_books_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_date',
        ),
    ]
