# Generated by Django 5.0.6 on 2024-07-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_books_book_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReg',
        ),
    ]
